name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
      TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
      TINA_BRANCH: main
      ANALYTICS_ID: ""
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"
          cache: "pnpm"
      - uses: pnpm/action-setup@v4
        with:
          version: "10.22.0"
          run_install: false
      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile
      - name: Generar panel de TinaCMS
        run: pnpm run tinacms:build
      - name: Chequeo de tipos de Astro
        run: pnpm run astro check
      - name: Compilar proyecto
        run: pnpm build
